"""Shared constants for the engine pipeline."""

from __future__ import annotations

DEFAULT_SR = 22050
DEFAULT_HOP = 512
DEFAULT_TIME_SIGNATURE = 4
DEFAULT_TATUM_DIVISIONS = 2
DEFAULT_SECTION_SECONDS = 30.0

EPS = 1e-9
MIN_DURATION_S = 0.01
MIN_TEMPO_WINDOW_S = 1e-6
PROGRESS_JOIN_TIMEOUT_S = 0.2
